### ISSUE TITLE
Add mechanism to drop single serum sample from a given plate

### ISSUE THREAD

**Issue by anloes** [jbloomlab/seqneut-pipeline#15]
Instances may arise from experimental issues where removing a single serum sample from a plate is a merited. For instance, D042d182 from plate 5 has a slightly higher amount of spike in control detected in all wells, leading to curves that plateau with a max infectivity of less than 1. Currently, there are two ways that this sample could be removed should we choose to do so. The first would be to specify all wells from the dilution series for this sample as wells to drop, alternatively, all barcodes can be specified individually in the serum_titers_qc_exclusions section of the config.yml. Perhaps it would be useful to add a mechanism to do this more directly?

**Comment by jbloom** [comment]
Now it is possible to remove just individual serum-replicates from plates in version 2.0.0
