### ISSUE TITLE
The data which indicates that samples should be removed due to QC issues is removed when filtering is done from the config.yml

### ISSUE THREAD

**Issue by anloes** [jbloomlab/seqneut-pipeline#16]
Currently, the pipeline functions to remove samples when indicated in the QC and removal of QC flags is required in order to aggregate titers. A downside to this approach is that the data which indicated that a sample/well/barcode should be removed due to a QC issue is removed when that sample is specified as having triggered a QC failure. In addition, as samples are added manually to the config.yml for removal, this process provides a potential source of error, and as the data for the samples is removed it's difficult to determine if that removal was merited without adding it back in and rerunning the pipeline. 

For transparency, I think the manner in which samples are filtered should be revised. I suggest that we set reasonable filters which are specified in the config.yml. For some types of errors such as insufficient reads in a given sample well we can automatically filter these samples from the next step in the pipeline as soon as the plot which indicates that a sample failed this filter is generated. We can then generate a report similar to that shown below, which aggregates information regarding sample filtering from all plates. I think this will be additionally useful, as it may improve our ability to detect issues that are shared between plates. 
[qc_process_counts_summary.txt](https://github.com/jbloomlab/seqneut-pipeline/files/13733689/qc_process_counts_summary.txt)

For automatic filtering, I think the following types of errors are reasonable to be directly removed if a filter is flagged: insufficient counts for a given barcode or well, and min or max barcode and neut standard counts or fraction. These filters should primarily remove only wells where there is insufficient data for processing. Errors that would result in this type of removal would be variability in sample loading during pooling, and/or inaccurate loading of virus and/or spike-in control during plate processing.

**Comment by jbloom** [comment]
The filtering is now done automatically for the most part with modifications as needed, and the `process_plate` and `serum_titers` notebooks show things before they are dropped.

There is also now a final notebook that summarizes all QC, as well as YAML files doing the same.
