### ISSUE TITLE
update dms_variants version

### ISSUE THREAD

**Issue by ckikawa** [jbloomlab/seqneut-pipeline#24]
The current version of `dms_variants` uses a deprecated `scipy` module. After the updated version of `dms_variants` is released, update the `snakemake` environment and the `count_barcodes` environment used within the pipeline to specify this most recent version of `dms_variants`. Also considering pinning the `numpy` and `scipy` versions?

**Comment by jbloom** [comment]
@ckikawa, this should be fixed in version 2.0.1 of the pipeline.
