### ISSUE TITLE
Include a mechanism to indicate that titers that are estimated to be out of bounds in summary plots

### ISSUE THREAD

**Issue by anloes** [jbloomlab/seqneut-pipeline#30]
In summary plots, currently, we do not show titers for strains where the NT50 is estimated to be out of bounds of the assay if the curve does not contain a max infectivity value of at least a certain value (as designated in config). This is because these values are filtered prior to plotting. However, we also do not show titers for strains where the NT50 was unable to be calculated from the barcode counts data. As these are different results, I think it would be useful to be able to visually distinguish between these scenarios. In addition, it would be beneficial when a titer is out of bounds to indicate on the aggregate titers plot that the titer is at the upper or lower bound.

**Comment by jbloom** [comment]
I should be able to add reporting of this when I add the reporting of the `rmsd` in [this issue](https://github.com/jbloomlab/seqneut-pipeline/issues/33) as I have to update that part of the code anyway to add `rmsd`.
