### ISSUE TITLE
plate-level manual drops with 'serum-replicates' causes assertion error, same error as seen in #45

### ISSUE THREAD

**Issue by anloes** [jbloomlab/seqneut-pipeline#49]
I think I am seeing the same issue we resolved for barcodes and wells in specifying in manual drops for serum-replicates. The config specifies a plural, while the counts dataframe column is singular. Planning to add elif statement as before to resolve. See issue #45

**Comment by jbloom** [comment]
Sounds good. Go ahead and make a pull request.
